language: python

python:
  - 2.6
  - 2.7

env:
  - DJANGO="django>=1.3,<1.4"
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="https://github.com/django/django/archive/stable/1.5.x.tar.gz"
  - DJANGO="https://github.com/django/django/tarball/master"

matrix:
  include:
    - python: 3.2
      env: DJANGO="https://github.com/django/django/archive/stable/1.5.x.tar.gz"
    - python: 3.2
      env: DJANGO="https://github.com/django/django/tarball/master"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/stable/1.5.x.tar.gz"
    - env: DJANGO="https://github.com/django/django/tarball/master"

install:
  - pip install $DJANGO argparse --use-mirrors

script:
  - python runtests.py
