language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

env:
  - DJANGO="django>=1.3,<1.4"
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="django>=1.5,<1.6"
  - DJANGO="https://github.com/django/django/archive/1.6b1.tar.gz"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"

matrix:
  exclude:
    - python: 3.2
      env: DJANGO="django>=1.3,<1.4"
    - python: 3.2
      env: DJANGO="django>=1.4,<1.5"
    - python: 3.3
      env: DJANGO="django>=1.3,<1.4"
    - python: 3.3
      env: DJANGO="django>=1.4,<1.5"
    - python: 2.6
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"

install:
  - pip install $DJANGO -q --use-mirrors
  - if python --version 2>&1 >/dev/null | grep -E '^Python 2' -q;
      then TEST='test_coverage';
    else
      TEST='test';
    fi
  - if echo $TEST | grep 'coverage' -q;
      then pip install coverage django-coverage -q --use-mirrors;
    fi

script:
  - python -Wall `which django-admin.py` $TEST polymodels --pythonpath=`pwd` --settings=test_settings -v2
