dist: bionic
sudo: false
language: python
cache: pip
python:
  - 3.6
  - 3.7
stages:
  - lint
  - test
jobs:
  fast_finish: true
  include:
    - { stage: lint, env: TOXENV=flake8, python: 3.6 }
    - { stage: lint, env: TOXENV=isort, python: 3.6 }
    - stage: deploy
      if: tag IS present
      python: 3.6
      deploy:
        skip_existing: true
        provider: pypi
        user: charettes
        distributions: sdist bdist_wheel
        password:
          secure: Ie01sbW96JaUmw7FN50xF9rphHnsld07SJFZPUK/ElBDEahweNwbKyiEjL6QmqUSQXKM03Vyqtf8JTri2HBZIZ+hhjKAUQluQHErM2OxQFWVN+96cdVL5kMbCDFEgwtNxJT4e9XqrqZ1xGEgJg7GG3Oa/Ei7nLY6snYqUJZ/mTM=
        on:
          tags: true
install:
- pip install tox coveralls tox-travis
script:
- tox
after_success:
- if [ -f .coverage ]; then coveralls; fi
