language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=master

matrix:
  exclude:
    - python: 2.6
      env: DJANGO=1.7
    - python: 2.6
      env: DJANGO=1.8
    - python: 2.6
      env: DJANGO=master
    - python: 3.2
      env: DJANGO=1.4
    - python: 3.2
      env: DJANGO=master
    - python: 3.3
      env: DJANGO=1.4
    - python: 3.4
      env: DJANGO=1.4
    - python: 3.4
      env: DJANGO=1.5
    - python: 3.4
      env: DJANGO=1.6
  allow_failures:
    - env: DJANGO=master

install:
  pip install tox coveralls

script:
  tox -e `python -c 'import sys,os;print("py%d%d-"%sys.version_info[0:2]+os.environ["DJANGO"])'`

after_success:
  - coverage report -m
  - coveralls
